[buildPlans.IoZanCode]
family = "IoZanCode"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IoZanCode.variants]
  inherits = "ss16"

    [buildPlans.IoZanCode.variants.design]
    one = "no-base-long-top-serif"
    three = "two-arcs"
    four = "closed-non-crossing-serifless"
    five = "oblique-arched-serifless"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-b = "standard-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "serifless"
    capital-j = "flat-hook-serifless"
    capital-k = "straight-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-w = "straight-serifless"
    a = "double-storey-hook-inward-serifed-serifed"
    b = "toothless-rounded-serifless"
    c = "serifless"
    d = "toothless-rounded-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless"
    h = "straight-serifless"
    i = "serifless"
    j = "flat-hook-serifless"
    k = "symmetric-touching-serifless"
    l = "flat-tailed"
    m = "earless-corner-double-arch-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-straight-serifless"
    r = "hookless-serifless"
    s = "serifless"
    t = "flat-hook-asymmetric-short-neck2"
    u = "toothed-serifless"
    w = "straight-flat-top-serifless"
    y = "straight-serifless"
    long-s = "flat-hook-serifless"
    eszet = "traditional-flat-hook-serifless"
    lower-eth = "straight-bar"
    capital-thorn = "motion-serifed"
    lower-thorn = "motion-serifed"
    lower-alpha = "barred-serifed"
    lower-beta = "standard"
    capital-gamma = "serifless"
    capital-delta = "straight"
    lower-delta = "rounded"
    lower-iota = "flat-tailed"
    lower-lambda = "straight-turn"
    lower-mu = "toothless-rounded-serifless"
    lower-nu = "casual"
    lower-xi = "rounded"
    lower-pi = "tailless"
    lower-tau = "tailless"
    lower-phi = "cursive"
    lower-chi = "semi-chancery-curly-serifless"
    lower-psi = "serifless"
    partial-derivative = "straight-bar"
    cyrl-a = "double-storey-serifless"
    cyrl-ve = "standard-serifless"
    cyrl-capital-zhe = "curly"
    cyrl-zhe = "curly"
    cyrl-ze = "unilateral-bottom-inward-serifed"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    cyrl-el = "straight"
    cyrl-em = "flat-bottom-serifless"
    cyrl-u = "straight-serifless"
    cyrl-ef = "split-serifless"
    cyrl-yeri = "corner"
    cyrl-yery = "corner"
    cyrl-e = "serifless"
    tittle = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    asterisk = "penta-high"
    underscore = "high"
    caret = "medium"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    guillemet = "straight"
    number-sign = "upright"
    ampersand = "upper-open"
    at = "fourfold-solid-inner"
    dollar = "through"
    percent = "dots"
    bar = "natural-slope"
    question = "smooth"
    pilcrow = "low"
    micro-sign = "toothed-serifless"
    decorative-angle-brackets = "tall"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IoZanCode.ligations]
  inherits = "ml"

[buildPlans.IoZanCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZanCode.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IoZanCode.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IoZanCode.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IoZanCode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IoZanCode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
