name: Font Build

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build ${{ matrix.fontName }} font
    if: github.repository == 'AgatZan/font'
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    strategy:
      matrix:
        fontName: ["IoZanCode"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: iosevka
      - name: Install Iosevka
        shell: bash
        run: |
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint
      - name: Build Font ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          git clone --depth 1 https://github.com/be5invis/Iosevka.git
          cp -f private-build-plans.toml Iosevka/private-build-plans.toml
          ls -la
          cd Iosevka
          npm install
          npm run build -- ttf::${{ matrix.fontName }}
          cd ..
          zip -r ${{ matrix.fontName }}.zip Iosevka/dist/${{ matrix.fontName }}/TTF/
          echo "GENERATE ${{ matrix.fontName }}"
          ls -la
     
      - name: Setup core dependencies
        run: |
          sudo apt update -y -q
          sudo apt install software-properties-common -y -q
          sudo apt install python3-fontforge -y -q
          sudo apt install fuse -y -q
      - name: Fetch FontForge
        run: |
          curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" \
            --output fontforge
          chmod u+x fontforge
          echo Try appimage
          ./fontforge --version
          export PATH=`pwd`:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo Try appimage with path
          fontforge --version
          fontforge --version 2>&1 | grep libfontforge | awk '{print $NF}'
      - name: Build NerdFont ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip FontPatcher.zip -d FontPatcher/
          fontforge --script `pwd`/FontPatcher/font-patcher --version
          echo "BEFORE BUILD ${{ matrix.fontName }}"
          ls -la
          mkdir Iosevka/dist/${{ matrix.fontName }}/NF/
          echo `pwd`/Iosevka/dist/${{ matrix.fontName }}/NF
          echo `pwd`/iosevka/dist/${{ matrix.fontName }}/NF
          for file in `pwd`/Iosevka/dist/${{ matrix.fontName }}/TTF/*.ttf
          do
            fontforge --script `pwd`/FontPatcher/font-patcher -c --careful $file -out `pwd`/Iosevka/dist/${{ matrix.fontName }}/NF > /dev/null
            echo $file "OK"
          done   
          echo "AFTER BUILD ${{ matrix.fontName }}"
          ls -la
          ls -la Iosevka/dist/${{ matrix.fontName }}/NF/
          zip -r ${{ matrix.fontName }}NF.zip Iosevka/dist/${{ matrix.fontName }}/NF/
          pwd
          ls -la
      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fontName }}
          path: iosevka/${{ matrix.fontName }}.zip
          retention-days: 1
      - name: Release ${{ matrix.fontName }}NF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fontName }}NF
          path: iosevka/${{ matrix.fontName }}NF.zip
          retention-days: 1
      - uses: actions/download-artifact@v4
      - name: Generate SHA256 checksums ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          ls -la
          sha256sum ${{ matrix.fontName }}.zip > ${{ matrix.fontName }}.zip.sha256sum
          cat ${{ matrix.fontName }}.zip.sha256sum.sha256sum
          cat ${{ matrix.fontName }}.zip.sha256sum.sha256sum >> $GITHUB_ENV
          sha256sum ${{ matrix.fontName }}NF.zip > ${{ matrix.fontName }}NF.zip.sha256sum
          cat ${{ matrix.fontName }}NF.zip.sha256sum.sha256sum
          cat ${{ matrix.fontName }}NF.zip.sha256sum.sha256sum >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo "$GITHUB_ENV" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Upload zip ${{ matrix.fontName }}
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            iosevka/${{ matrix.fontName }}NF.zip
            iosevka/${{ matrix.fontName }}NF.zip.sha256sum           
            iosevka/${{ matrix.fontName }}.zip
            iosevka/${{ matrix.fontName }}.zip.sha256sum 

